// =============================================================================
// DocuSign eSign Integration
//
// Uses JWT Bearer Grant for server-to-server authentication.
// No OAuth redirect flow — the service account impersonates the DocuSign
// admin user to create and manage envelopes on behalf of the platform.
//
// Required environment variables:
//   DOCUSIGN_INTEGRATION_KEY  — Application integration key (client ID)
//   DOCUSIGN_USER_ID          — The DocuSign user UUID to impersonate
//   DOCUSIGN_ACCOUNT_ID       — DocuSign account UUID
//   DOCUSIGN_PRIVATE_KEY      — RSA private key, base64-encoded
//   DOCUSIGN_BASE_PATH        — e.g. "https://demo.docusign.net/restapi" (sandbox)
//                               or  "https://na3.docusign.net/restapi" (production)
//   DOCUSIGN_OAUTH_HOST       — "account-d.docusign.com" (sandbox)
//                               or "account.docusign.com" (production)
//
// Setup:
//   1. Create an application in DocuSign Developer portal.
//   2. Generate an RSA keypair in the app settings; paste the private key,
//      base64-encoded, into DOCUSIGN_PRIVATE_KEY.
//   3. Grant consent: visit the consent URL once per environment
//      https://{DOCUSIGN_OAUTH_HOST}/oauth/auth?response_type=code&scope=signature%20impersonation&client_id={INTEGRATION_KEY}&redirect_uri=https://YOUR_APP/auth/docusign/callback
//   4. Configure DocuSign Connect (webhook) pointing to:
//      POST {APP_URL}/api/webhooks/docusign
//      Trigger events: envelope-completed, recipient-completed
//      HMAC key: set DOCUSIGN_WEBHOOK_SECRET and register the same value in Connect.
// =============================================================================

import crypto from 'crypto'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface DocuSignSigner {
  /** User's full name, shown in DocuSign UI */
  name:         string
  /** Email address — used to identify the signer in the envelope */
  email:        string
  /**
   * Our platform's user UUID. Used as clientUserId for embedded signing.
   * When set, DocuSign does NOT send email notifications — the user signs
   * via a RecipientView URL generated by getSigningUrl().
   */
  clientUserId: string
  /** 1-based routing order. Lower numbers sign first. */
  routingOrder: number
}

export interface CreateEnvelopeInput {
  /** Deal UUID — used as the envelope subject and metadata */
  dealId:       string
  /** Subject line shown in DocuSign (for audit trail, not visible in embedded flow) */
  subject:      string
  /** PDF file contents — the unsigned contract document */
  pdfBuffer:    Buffer
  /** Original filename, shown in DocuSign UI */
  fileName:     string
  /** Funder signer details */
  funder:       DocuSignSigner
  /** Contractor signer details */
  contractor:   DocuSignSigner
}

export interface CreateEnvelopeResult {
  envelopeId: string
  status:     string
}

export interface GetSigningUrlInput {
  envelopeId:  string
  signer:      DocuSignSigner
  /** URL to redirect to after signing (or declining). Your app's deal page. */
  returnUrl:   string
}

// ─── Token Cache ─────────────────────────────────────────────────────────────
// Access tokens are valid for 1 hour. Cache to avoid a JWT roundtrip per request.

let _tokenCache: { token: string; expiresAtMs: number } | null = null

// ─── JWT Helpers ──────────────────────────────────────────────────────────────

function base64url(input: Buffer | string): string {
  const buf = typeof input === 'string' ? Buffer.from(input, 'utf-8') : input
  return buf.toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '')
}

function buildJwt(): string {
  const integrationKey = requiredEnv('DOCUSIGN_INTEGRATION_KEY')
  const userId         = requiredEnv('DOCUSIGN_USER_ID')
  const oauthHost      = requiredEnv('DOCUSIGN_OAUTH_HOST')
  const privateKeyB64  = requiredEnv('DOCUSIGN_PRIVATE_KEY')
  const privateKey     = Buffer.from(privateKeyB64, 'base64').toString('utf-8')

  const now = Math.floor(Date.now() / 1000)

  const header  = base64url(JSON.stringify({ alg: 'RS256', typ: 'JWT' }))
  const payload = base64url(JSON.stringify({
    iss:   integrationKey,
    sub:   userId,
    aud:   oauthHost,
    iat:   now,
    exp:   now + 3600,
    scope: 'signature impersonation',
  }))

  const signingInput = `${header}.${payload}`
  const signer       = crypto.createSign('RSA-SHA256')
  signer.update(signingInput)
  const sig = signer.sign(privateKey, 'base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '')

  return `${signingInput}.${sig}`
}

// ─── Authentication ───────────────────────────────────────────────────────────

async function getAccessToken(): Promise<string> {
  // Return cached token if still valid (with a 60s buffer)
  if (_tokenCache && Date.now() < _tokenCache.expiresAtMs - 60_000) {
    return _tokenCache.token
  }

  const oauthHost = requiredEnv('DOCUSIGN_OAUTH_HOST')
  const jwt       = buildJwt()

  const res = await fetch(`https://${oauthHost}/oauth/token`, {
    method:  'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body:    new URLSearchParams({
      grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
      assertion:  jwt,
    }),
  })

  if (!res.ok) {
    const body = await res.text()
    throw new DocuSignError(
      `DocuSign JWT auth failed (${res.status}): ${body}. ` +
      'Ensure DOCUSIGN_INTEGRATION_KEY, DOCUSIGN_USER_ID, DOCUSIGN_PRIVATE_KEY are correct ' +
      'and that consent has been granted for the impersonated user.',
    )
  }

  const data = await res.json() as { access_token: string; expires_in: number }
  _tokenCache = {
    token:       data.access_token,
    expiresAtMs: Date.now() + (data.expires_in ?? 3600) * 1000,
  }

  return _tokenCache.token
}

// ─── API Request Helper ───────────────────────────────────────────────────────

async function dsRequest<T>(
  method:   'GET' | 'POST' | 'PUT' | 'DELETE',
  path:     string,
  body?:    unknown,
): Promise<T> {
  const token      = await getAccessToken()
  const accountId  = requiredEnv('DOCUSIGN_ACCOUNT_ID')
  const basePath   = requiredEnv('DOCUSIGN_BASE_PATH')
  const url        = `${basePath}/v2.1/accounts/${accountId}${path}`

  const res = await fetch(url, {
    method,
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type':  'application/json',
      'Accept':        'application/json',
    },
    body: body ? JSON.stringify(body) : undefined,
  })

  if (!res.ok) {
    const errBody = await res.text()
    throw new DocuSignError(
      `DocuSign API error ${res.status} on ${method} ${path}: ${errBody}`,
    )
  }

  return res.json() as Promise<T>
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Creates a DocuSign envelope with the contract PDF and two signers.
 *
 * Uses embedded (clientUserId) recipients — DocuSign does NOT send email
 * notifications. The funder and contractor receive signing links via the
 * Vektrum platform (see getSigningUrl).
 *
 * Signing order: funder (routing order 1) → contractor (routing order 2).
 * Contractor's signing session becomes available only after the funder signs.
 */
export async function createEnvelope(input: CreateEnvelopeInput): Promise<CreateEnvelopeResult> {
  const { dealId, subject, pdfBuffer, fileName, funder, contractor } = input

  const envelope = {
    emailSubject: subject,
    status:       'sent',

    documents: [
      {
        documentId:   '1',
        name:         fileName,
        documentBase64: pdfBuffer.toString('base64'),
        fileExtension: 'pdf',
      },
    ],

    recipients: {
      signers: [
        buildSigner(funder,     '1'),
        buildSigner(contractor, '2'),
      ],
    },

    customFields: {
      textCustomFields: [
        { name: 'vektrum_deal_id',   value: dealId,   show: 'false', required: 'false' },
        { name: 'vektrum_platform',  value: 'vektrum', show: 'false', required: 'false' },
      ],
    },
  }

  const result = await dsRequest<{ envelopeId: string; status: string }>(
    'POST',
    '/envelopes',
    envelope,
  )

  return {
    envelopeId: result.envelopeId,
    status:     result.status,
  }
}

/**
 * Returns a one-time-use URL that opens the DocuSign signing session
 * in the user's browser.
 *
 * The URL expires shortly after creation (typically 5 minutes).
 * Regenerate if the user doesn't use it immediately.
 *
 * The returnUrl receives a `?event=` query parameter from DocuSign:
 *   - signing_complete — signer finished
 *   - decline          — signer declined
 *   - session_timeout  — session timed out
 *   - ttl_expired      — URL was not used in time
 *   - viewing_complete — viewer only (no action taken)
 */
export async function getSigningUrl(input: GetSigningUrlInput): Promise<string> {
  const { envelopeId, signer, returnUrl } = input

  const body = {
    clientUserId:  signer.clientUserId,
    email:         signer.email,
    userName:      signer.name,
    returnUrl,
    authenticationMethod: 'none',
  }

  const result = await dsRequest<{ url: string }>(
    'POST',
    `/envelopes/${envelopeId}/views/recipient`,
    body,
  )

  return result.url
}

/**
 * Fetches the current status of an envelope from DocuSign.
 * Use this for polling when webhooks are unavailable.
 */
export async function getEnvelopeStatus(envelopeId: string): Promise<{
  status:     string
  recipients: { signers: Array<{ email: string; clientUserId: string; status: string; signedDateTime?: string }> }
}> {
  return dsRequest('GET', `/envelopes/${envelopeId}?include=recipients`)
}

/**
 * Voids an envelope. Call this when a contract is cancelled or a new
 * version needs to be uploaded.
 */
export async function voidEnvelope(envelopeId: string, reason: string): Promise<void> {
  await dsRequest('PUT', `/envelopes/${envelopeId}`, {
    status:      'voided',
    voidedReason: reason.slice(0, 200), // DocuSign max length
  })
}

/**
 * Downloads the final signed PDF from DocuSign after the envelope completes.
 * Returns a Buffer of the combined PDF.
 */
export async function downloadSignedDocument(envelopeId: string): Promise<Buffer> {
  const token     = await getAccessToken()
  const accountId = requiredEnv('DOCUSIGN_ACCOUNT_ID')
  const basePath  = requiredEnv('DOCUSIGN_BASE_PATH')

  const url = `${basePath}/v2.1/accounts/${accountId}/envelopes/${envelopeId}/documents/combined`
  const res = await fetch(url, {
    headers: { 'Authorization': `Bearer ${token}` },
  })

  if (!res.ok) {
    throw new DocuSignError(`Failed to download signed document for envelope ${envelopeId}: ${res.status}`)
  }

  const arrayBuffer = await res.arrayBuffer()
  return Buffer.from(arrayBuffer)
}

// ─── Webhook Verification ─────────────────────────────────────────────────────

/**
 * Verifies the HMAC-SHA256 signature on a DocuSign Connect webhook request.
 *
 * DocuSign sends `X-DocuSign-Signature-1` containing the base64-encoded
 * HMAC-SHA256 of the raw request body with the webhook secret as key.
 *
 * Register the same secret in: DocuSign Admin → Connect → HMAC Keys.
 */
export function verifyWebhookSignature(
  rawBody:   Buffer,
  signature: string,
  secret:    string,
): boolean {
  const expected = crypto
    .createHmac('sha256', secret)
    .update(rawBody)
    .digest('base64')
  return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature))
}

/**
 * Returns true ONLY when webhook HMAC verification may safely be skipped.
 *
 * Two conditions must BOTH be true simultaneously:
 *   1. NODE_ENV === 'development'   — rules out all deployed environments.
 *      Next.js sets NODE_ENV='production' for every Vercel deployment,
 *      including preview branches and staging — so the bypass is impossible
 *      in any deployed context regardless of the second flag.
 *   2. DOCUSIGN_WEBHOOK_DEV_BYPASS === 'true' — explicit per-developer opt-in.
 *      This must never appear in staging, preview, or production env files.
 *
 * Rationale: the old check (`NODE_ENV !== 'production'`) was fragile because
 * non-Next.js runners (Jest, custom scripts, Node servers) may set NODE_ENV
 * to 'test', 'staging', or another non-production value while actually being
 * reachable by real DocuSign Connect webhooks. A missing HMAC secret in that
 * situation would allow unsigned requests to mutate deal and contract state.
 *
 * Exported so the route can call it with process.env and tests can call it
 * with synthetic env objects — no process.env mutation needed in tests.
 */
export function isHmacBypassAllowed(
  env: Pick<NodeJS.ProcessEnv, 'NODE_ENV' | 'DOCUSIGN_WEBHOOK_DEV_BYPASS'>,
): boolean {
  return env.NODE_ENV === 'development' && env.DOCUSIGN_WEBHOOK_DEV_BYPASS === 'true'
}

// ─── Webhook Payload Types ────────────────────────────────────────────────────

export interface DocuSignWebhookEvent {
  event:          string   // e.g. "envelope-completed", "recipient-completed"
  apiVersion:     string
  uri:            string
  retryCount:     number
  configurationId: number
  generatedDateTime: string
  data: {
    accountId:   string
    envelopeId:  string
    envelopeSummary: {
      status:              string   // 'completed', 'sent', 'delivered', 'declined', 'voided'
      envelopeId:          string
      emailSubject:        string
      sentDateTime?:       string
      completedDateTime?:  string
      voidedDateTime?:     string
      voidedReason?:       string
      recipients: {
        signers: Array<{
          email:            string
          name:             string
          clientUserId?:    string
          status:           string  // 'completed', 'sent', 'delivered', 'declined'
          signedDateTime?:  string
          routingOrder:     string
        }>
      }
    }
  }
}

// ─── Internal Helpers ─────────────────────────────────────────────────────────

function buildSigner(signer: DocuSignSigner, recipientId: string) {
  return {
    recipientId:   recipientId,
    name:          signer.name,
    email:         signer.email,
    clientUserId:  signer.clientUserId,
    routingOrder:  String(signer.routingOrder),
    tabs: {
      signHereTabs: [
        {
          // Anchor-based positioning. The contract PDF should contain the text
          // "\s1\" (funder) or "\s2\" (contractor). If not present, DocuSign
          // falls back to the bottom of the last page.
          anchorString:     `\\s${signer.routingOrder}\\`,
          anchorUnits:      'pixels',
          anchorXOffset:    '0',
          anchorYOffset:    '0',
          anchorIgnoreIfNotPresent: 'true',
          // Absolute fallback: bottom of page 1 if anchor not found
          pageNumber:       '1',
          xPosition:        '72',
          yPosition:        '680',
        },
      ],
      dateSignedTabs: [
        {
          anchorString:     `\\d${signer.routingOrder}\\`,
          anchorUnits:      'pixels',
          anchorIgnoreIfNotPresent: 'true',
          pageNumber:       '1',
          xPosition:        '250',
          yPosition:        '680',
        },
      ],
    },
  }
}

function requiredEnv(key: string): string {
  const val = process.env[key]
  if (!val) {
    throw new DocuSignError(
      `Missing required environment variable: ${key}. ` +
      'See src/lib/engine/docusign.ts for the full list of required DocuSign env vars.',
    )
  }
  return val
}

export class DocuSignError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'DocuSignError'
  }
}
