import type { Metadata } from 'next'
import Link from 'next/link'
import {
  ArrowLeft,
  CheckCircle2,
  Clock,
  FileText,
  Shield,
  ShieldCheck,
  XCircle,
  AlertCircle,
  Fingerprint,
  ChevronRight,
} from 'lucide-react'

export const revalidate = 3600

export const metadata: Metadata = {
  title: 'Release Authorization Walkthrough | Vektrum Demo',
  description:
    'See the full release authorization cycle in 6 steps: contractor submits, AI reviews evidence, the gate evaluates 10 conditions, a blocker is resolved, and the authorization token is issued with an audit proof.',
  alternates: { canonical: 'https://vektrum.io/demo-live/walkthrough' },
}

// ─── Step data ────────────────────────────────────────────────────────────────

interface WalkthroughStep {
  number:    number
  phase:     string
  actor:     'Contractor' | 'AI' | 'Gate' | 'Funder' | 'System'
  actorColor: string
  title:     string
  body:      string
  status:    'completed' | 'blocked' | 'resolved' | 'authorized'
  detail:    React.ReactNode
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function WalkthroughPage() {
  return (
    <div className="relative min-h-screen bg-surface-0 overflow-hidden">

      {/* Ambient glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[350px] bg-gradient-to-b from-vektrum-blue/10 to-transparent rounded-full blur-3xl pointer-events-none" aria-hidden="true" />

      <div className="relative max-w-3xl mx-auto px-6 sm:px-8 pt-20 pb-28">

        {/* Back nav */}
        <nav className="mb-10">
          <Link
            href="/demo-live"
            className="inline-flex items-center gap-1.5 text-[12px] text-white/50 hover:text-white transition-colors"
          >
            <ArrowLeft size={12} aria-hidden="true" />
            Back to demo
          </Link>
        </nav>

        {/* Header */}
        <div className="mb-14">
          <div className="inline-flex items-center gap-3 mb-5">
            <div className="h-px w-5 bg-vektrum-blue" aria-hidden="true" />
            <p className="text-[11px] tracking-[0.12em] uppercase text-blue-300 font-semibold">
              Guided walkthrough
            </p>
            <div className="h-px w-5 bg-vektrum-blue" aria-hidden="true" />
          </div>
          <h1 className="font-display text-[2.25rem] sm:text-[2.75rem] font-bold tracking-[-0.04em] text-white leading-[1.05] mb-4">
            From draw submission to<br className="hidden sm:block" /> authorized release.
          </h1>
          <p className="text-[15px] leading-relaxed text-white/55 max-w-xl">
            This walkthrough shows a realistic draw cycle on the Riverside Avenue
            Multifamily deal — including a gate blocker that must be resolved before
            authorization is granted. All data is simulated; no real funds are involved.
          </p>
        </div>

        {/* Steps */}
        <div className="space-y-0">

          {/* ── Step 1 ── */}
          <Step
            number={1}
            phase="Draw submission"
            actor="Contractor"
            actorColor="text-emerald-400"
            title="Contractor submits draw request with evidence"
            status="completed"
            last={false}
          >
            <DemoCard variant="green" label="Draw #3 — Foundation & Framing">
              <Row label="Milestone"    value="Foundation & Framing" />
              <Row label="Amount"       value="$184,000" />
              <Row label="Status"       value={<Badge color="amber">Submitted for review</Badge>} />
              <Row label="Evidence"     value="3 documents attached" />
              <DocRow name="Webb_Invoice_2044.pdf"     type="Invoice" />
              <DocRow name="Inspection_Report_3B.pdf"  type="Inspection" />
              <DocRow name="Site_Photo_Progress.jpg"   type="Photo" />
            </DemoCard>
            <p className="mt-3 text-[12px] text-white/50 leading-relaxed">
              Contractor Marcus Webb (Webb Construction Group) submits the draw
              package. Vektrum records each document as evidence against the
              milestone before the review begins.
            </p>
          </Step>

          {/* ── Step 2 ── */}
          <Step
            number={2}
            phase="AI evidence review"
            actor="AI"
            actorColor="text-blue-300"
            title="Draw Control Brief generated by Perplexity"
            status="completed"
            last={false}
          >
            <DemoCard variant="blue" label="Draw Control Brief — Foundation & Framing">
              <Row label="AI provider"  value="Perplexity sonar-pro" />
              <Row label="Risk level"   value={<Badge color="green">Low</Badge>} />
              <Row label="Findings"     value="2 findings (informational)" />
              <Row label="Evidence"     value={<Badge color="green">Sufficient</Badge>} />
              <Row label="AI informs?"  value={<span className="text-white/80">Yes — funder decides</span>} />
            </DemoCard>
            <p className="mt-3 text-[12px] text-white/50 leading-relaxed">
              Perplexity reads the draw package and produces a structured Draw Control
              Brief. Two informational findings are flagged (minor scope notes). No
              critical risk. The AI informs — it does not approve; the release gate
              and funder authorization control release.
            </p>
          </Step>

          {/* ── Step 3 ── */}
          <Step
            number={3}
            phase="Release gate"
            actor="Gate"
            actorColor="text-amber-400"
            title="10-condition release gate runs — 1 condition fails"
            status="blocked"
            last={false}
          >
            <DemoCard variant="amber" label="Release Gate — 10 Conditions">
              <GateRow label="1. Milestone approved"              pass />
              <GateRow label="2. Protection status ready"         pass />
              <GateRow label="3. Sufficient funding"             pass />
              <GateRow label="4. Payout readiness verified"      pass />
              <GateRow label="5. Contractor onboarding complete" pass />
              <GateRow label="6. No active duplicate release"    pass />
              <GateRow label="7. No open change orders"          pass />
              <GateRow label="8. Signed contract on file"        pass />
              <GateRow label="9. Sequential prerequisites met"   pass />
              <GateRow label="10. Approved lien waiver on file"  pass={false} />
            </DemoCard>
            <div className="mt-3 flex items-start gap-2 rounded-lg border border-amber-500/20 bg-amber-500/[0.06] px-3.5 py-3 text-[12px] text-amber-400">
              <AlertCircle size={13} className="mt-0.5 flex-shrink-0" aria-hidden="true" />
              <span>
                <strong>Release blocked.</strong>{' '}
                Condition 10 fails: a conditional lien waiver is required for this
                milestone. The funder must request it from the contractor before
                release can be authorized. No payment is initiated.
              </span>
            </div>
          </Step>

          {/* ── Step 4 ── */}
          <Step
            number={4}
            phase="Blocker resolution"
            actor="Funder"
            actorColor="text-blue-300"
            title="Funder requests lien waiver from contractor"
            status="resolved"
            last={false}
          >
            <DemoCard variant="neutral" label="Lien Waiver Request — #LW-2044">
              <Row label="Deal"         value="Riverside Avenue Multifamily" />
              <Row label="Milestone"    value="Foundation & Framing" />
              <Row label="Requested by" value="Sarah Chen (Meridian Capital)" />
              <Row label="Status"       value={<Badge color="amber">Awaiting upload</Badge>} />
              <Row label="Type"         value="Conditional waiver on release" />
            </DemoCard>
            <p className="mt-3 text-[12px] text-white/50 leading-relaxed">
              Funder Sarah Chen clicks "Request lien waiver" on the milestone. Vektrum
              creates a waiver record and sends a notification to Marcus Webb. The gate
              condition remains blocked until an approved waiver is on file.
            </p>
          </Step>

          {/* ── Step 5 ── */}
          <Step
            number={5}
            phase="Condition resolved"
            actor="Contractor"
            actorColor="text-emerald-400"
            title="Contractor uploads lien waiver — condition cleared"
            status="resolved"
            last={false}
          >
            <DemoCard variant="green" label="Lien Waiver #LW-2044 — Uploaded">
              <Row label="Document"     value="LienWaiver_Foundation_WBB.pdf" />
              <Row label="Uploaded by"  value="Marcus Webb" />
              <Row label="Type"         value="Conditional on release" />
              <Row label="Status"       value={<Badge color="green">Approved</Badge>} />
              <Row label="Condition 10" value={<Badge color="green">✓ Cleared</Badge>} />
            </DemoCard>
            <p className="mt-3 text-[12px] text-white/50 leading-relaxed">
              Marcus uploads the signed conditional waiver. Vektrum records the
              document, the funder reviews and approves it, and Condition 10 is
              cleared. All 10 gate conditions now pass.
            </p>
          </Step>

          {/* ── Step 6 ── */}
          <Step
            number={6}
            phase="Authorization"
            actor="System"
            actorColor="text-blue-300"
            title="Release authorized — token issued, audit proof captured"
            status="authorized"
            last
          >
            <DemoCard variant="blue" label="Authorization Token — AT-7G4K2">
              <Row label="Token ID (JTI)"  value="at-7g4k2-...f91a" />
              <Row label="Milestone"       value="Foundation & Framing" />
              <Row label="Amount"          value="$184,000" />
              <Row label="Rail"            value="Stripe Connect" />
              <Row label="Signature"       value={<Badge color="green">ed25519 signed</Badge>} />
              <Row label="Policy version"  value="10-condition-gate.v1" />
              <Row label="Status"          value={<Badge color="green">Confirmed</Badge>} />
            </DemoCard>
            <div className="mt-3 space-y-2">
              <AuditEntry
                action="release_authorized"
                actor="Sarah Chen"
                note="All 10 conditions passed. Authorization token issued."
              />
              <AuditEntry
                action="funds_released"
                actor="system"
                note="token_hash bound. audit chain: verified."
              />
            </div>
            <p className="mt-3 text-[12px] text-white/50 leading-relaxed">
              All 10 conditions pass. Vektrum issues a cryptographically signed
              authorization token (ed25519), records the release with the token hash
              bound into the append-only audit chain, and dispatches to the payment
              rail. Vektrum governs; the rail executes. No funds are held by Vektrum.
            </p>
          </Step>

        </div>

        {/* Summary callout */}
        <div className="mt-14 rounded-2xl border border-vektrum-blue/20 bg-vektrum-blue/[0.04] px-7 py-6 space-y-3">
          <div className="flex items-center gap-2.5">
            <ShieldCheck size={16} className="text-blue-300 flex-shrink-0" aria-hidden="true" />
            <p className="text-[13px] font-semibold text-white">
              What this demo shows
            </p>
          </div>
          <ul className="space-y-2 text-[12px] text-white/60 leading-relaxed">
            <li className="flex items-start gap-2">
              <ChevronRight size={10} className="mt-1 flex-shrink-0 text-blue-300/60" aria-hidden="true" />
              <span>The release gate is deterministic — it checks all 10 conditions. One failure blocks the entire release.</span>
            </li>
            <li className="flex items-start gap-2">
              <ChevronRight size={10} className="mt-1 flex-shrink-0 text-blue-300/60" aria-hidden="true" />
              <span>AI reviews evidence and produces a brief. It never approves releases — the gate and funder authorization decide.</span>
            </li>
            <li className="flex items-start gap-2">
              <ChevronRight size={10} className="mt-1 flex-shrink-0 text-blue-300/60" aria-hidden="true" />
              <span>Every release produces an authorization token and an audit proof bound into an append-only, tamper-evident chain.</span>
            </li>
            <li className="flex items-start gap-2">
              <ChevronRight size={10} className="mt-1 flex-shrink-0 text-blue-300/60" aria-hidden="true" />
              <span>Vektrum does not hold funds. Payment execution runs through Stripe Connect or your existing wire/ACH/escrow process.</span>
            </li>
          </ul>
        </div>

        {/* Footer CTAs */}
        <div className="mt-10 flex flex-col sm:flex-row gap-3">
          <Link
            href="/demo-live/funder?tour=1"
            className="inline-flex items-center justify-center gap-2 rounded-xl bg-vektrum-blue px-5 py-3 text-[13px] font-semibold text-white hover:bg-vektrum-blue-hover transition-colors"
          >
            <Shield size={14} aria-hidden="true" />
            Try the funder demo
          </Link>
          <Link
            href="/demo-live"
            className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/[0.10] bg-transparent px-5 py-3 text-[13px] font-semibold text-white/70 hover:text-white hover:border-white/[0.18] transition-colors"
          >
            <ArrowLeft size={13} aria-hidden="true" />
            Choose a role
          </Link>
        </div>

        {/* Disclaimer */}
        <p className="mt-8 text-[11px] text-white/30 leading-relaxed">
          No real funds &nbsp;·&nbsp; No real accounts &nbsp;·&nbsp;
          All data is simulated &nbsp;·&nbsp; Vektrum does not hold or move funds
        </p>

      </div>
    </div>
  )
}

// ─── Sub-components ────────────────────────────────────────────────────────────

function Step({
  number,
  phase,
  actor,
  actorColor,
  title,
  status,
  last,
  children,
}: {
  number:     number
  phase:      string
  actor:      string
  actorColor: string
  title:      string
  status:     'completed' | 'blocked' | 'resolved' | 'authorized'
  last:       boolean
  children:   React.ReactNode
}) {
  const statusIcon = {
    completed:  <CheckCircle2 size={13} className="text-emerald-400" />,
    blocked:    <XCircle      size={13} className="text-amber-400" />,
    resolved:   <CheckCircle2 size={13} className="text-emerald-400" />,
    authorized: <Fingerprint  size={13} className="text-blue-300" />,
  }[status]

  const statusLabel = {
    completed:  'Done',
    blocked:    'Blocked',
    resolved:   'Resolved',
    authorized: 'Authorized',
  }[status]

  return (
    <div className="relative flex gap-5">
      {/* Spine */}
      <div className="flex flex-col items-center">
        <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full border border-white/[0.12] bg-surface-2 text-[12px] font-bold text-white/70">
          {number}
        </div>
        {!last && (
          <div className="mt-1 w-px flex-1 bg-white/[0.06]" aria-hidden="true" />
        )}
      </div>

      {/* Content */}
      <div className={`pb-12 flex-1 min-w-0 ${last ? 'pb-0' : ''}`}>
        <div className="flex flex-wrap items-center gap-2 mb-1">
          <span className="text-[10px] font-bold uppercase tracking-[0.12em] text-white/30">
            {phase}
          </span>
          <span className={`text-[10px] font-semibold ${actorColor}`}>
            · {actor}
          </span>
          <span className="ml-auto flex items-center gap-1 text-[10px] text-white/40">
            {statusIcon}
            {statusLabel}
          </span>
        </div>
        <h2 className="text-[15px] font-semibold text-white leading-snug mb-4">
          {title}
        </h2>
        {children}
      </div>
    </div>
  )
}

function DemoCard({
  variant,
  label,
  children,
}: {
  variant: 'green' | 'blue' | 'amber' | 'neutral'
  label:   string
  children: React.ReactNode
}) {
  const border = {
    green:   'border-emerald-500/20',
    blue:    'border-vektrum-blue/25',
    amber:   'border-amber-500/20',
    neutral: 'border-white/[0.08]',
  }[variant]

  const headerBg = {
    green:   'bg-emerald-500/[0.05]',
    blue:    'bg-vektrum-blue/[0.06]',
    amber:   'bg-amber-500/[0.05]',
    neutral: 'bg-white/[0.02]',
  }[variant]

  return (
    <div className={`rounded-xl border ${border} overflow-hidden`}>
      <div className={`px-4 py-2.5 border-b ${border} ${headerBg}`}>
        <p className="text-[11px] font-semibold text-white/65">{label}</p>
      </div>
      <div className="px-4 py-3 space-y-2 font-mono text-[11px]">
        {children}
      </div>
    </div>
  )
}

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-center justify-between gap-3">
      <span className="text-white/35 shrink-0">{label}</span>
      <span className="text-white/80 text-right">{value}</span>
    </div>
  )
}

function DocRow({ name, type }: { name: string; type: string }) {
  return (
    <div className="flex items-center gap-2 pl-2">
      <FileText size={10} className="text-white/25 flex-shrink-0" aria-hidden="true" />
      <span className="text-white/55 truncate">{name}</span>
      <span className="ml-auto text-white/30 shrink-0">{type}</span>
    </div>
  )
}

function GateRow({ label, pass }: { label: string; pass: boolean }) {
  return (
    <div className="flex items-center gap-2">
      {pass
        ? <CheckCircle2 size={11} className="text-emerald-400 flex-shrink-0" aria-hidden="true" />
        : <XCircle      size={11} className="text-amber-400  flex-shrink-0" aria-hidden="true" />
      }
      <span className={pass ? 'text-white/60' : 'text-amber-400 font-semibold'}>{label}</span>
    </div>
  )
}

function Badge({
  color,
  children,
}: {
  color: 'green' | 'amber' | 'blue'
  children: React.ReactNode
}) {
  const cls = {
    green: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    amber: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    blue:  'bg-vektrum-blue/10 text-blue-300 border-vektrum-blue/30',
  }[color]
  return (
    <span className={`inline-flex items-center rounded-md border px-1.5 py-0.5 text-[10px] font-semibold ${cls}`}>
      {children}
    </span>
  )
}

function AuditEntry({
  action,
  actor,
  note,
}: {
  action: string
  actor:  string
  note:   string
}) {
  return (
    <div className="flex items-start gap-2 rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-2 font-mono text-[11px]">
      <Shield size={10} className="mt-0.5 text-blue-300 flex-shrink-0" aria-hidden="true" />
      <div className="min-w-0 flex-1">
        <span className="text-blue-300 font-semibold">{action}</span>
        <span className="text-white/30 mx-1.5">·</span>
        <span className="text-white/50">{actor}</span>
        <p className="mt-0.5 text-white/35 leading-relaxed">{note}</p>
      </div>
    </div>
  )
}
